name: "Build and cache service provider"
on:
  push: 
    branches: [ main, 'main-**' ]
  pull_request: 
    branches: [ main, 'main-**' ]

jobs:
  build-and-cache-provider:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.11

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio
      
      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2

      - name: Build provider
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#safehold-service-provider
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#safehold-service-provider | jq -r 'keys[0]')

          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#safehold-service-provider.meta.debug
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#safehold-service-provider.meta.debug | jq -r 'keys[0]')

      - name: Pin provider
        if: github.event_name != 'pull_request' && github.ref_name == 'main-0.5'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix pin darksoil-studio safehold-service-provider  $(nix path-info --json --accept-flake-config --no-warn-dirty .#safehold-service-provider  | jq -r 'keys[0]')
          cachix pin darksoil-studio safehold-service-provider  $(nix path-info --json --accept-flake-config --no-warn-dirty .#safehold-service-provider.meta.debug | jq -r 'keys[0]')

      - name: Build client
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#safehold-service-client
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#safehold-service-client | jq -r 'keys[0]')

          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#safehold-service-client.meta.debug
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#safehold-service-client.meta.debug | jq -r 'keys[0]')

      - name: Pin client
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix pin darksoil-studio safehold-service-client  $(nix path-info --json --accept-flake-config --no-warn-dirty .#safehold-service-client  | jq -r 'keys[0]')
          cachix pin darksoil-studio safehold-service-client  $(nix path-info --json --accept-flake-config --no-warn-dirty .#safehold-service-client.meta.debug | jq -r 'keys[0]')
